package com.codingbingo.fastreader.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BOOK".
 */
@Entity
public class Book {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String bookName;
    private String bookImagePath;
    private String description;
    private String tags;
    private String writer;
    private String charSet;
    private String bookPath;
    private int processStatus;

    @Generated
    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    @Generated
    public Book(Long id, String bookName, String bookImagePath, String description, String tags, String writer, String charSet, String bookPath, int processStatus) {
        this.id = id;
        this.bookName = bookName;
        this.bookImagePath = bookImagePath;
        this.description = description;
        this.tags = tags;
        this.writer = writer;
        this.charSet = charSet;
        this.bookPath = bookPath;
        this.processStatus = processStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getBookName() {
        return bookName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookName(@NotNull String bookName) {
        this.bookName = bookName;
    }

    public String getBookImagePath() {
        return bookImagePath;
    }

    public void setBookImagePath(String bookImagePath) {
        this.bookImagePath = bookImagePath;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getWriter() {
        return writer;
    }

    public void setWriter(String writer) {
        this.writer = writer;
    }

    public String getCharSet() {
        return charSet;
    }

    public void setCharSet(String charSet) {
        this.charSet = charSet;
    }

    public String getBookPath() {
        return bookPath;
    }

    public void setBookPath(String bookPath) {
        this.bookPath = bookPath;
    }

    public int getProcessStatus() {
        return processStatus;
    }

    public void setProcessStatus(int processStatus) {
        this.processStatus = processStatus;
    }

}
